# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BetterProfessor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterProfessor
  pod 'SwiftLint'
  target 'BetterProfessorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterProfessorUITests' do
    # Pods for testing
  end

end
